-- Active: 1783779183123@@127.0.0.1@3306@ecom
CREATE TABLE products (
    product_id INT PRIMARY KEY,
    name VARCHAR(50),
    price DECIMAL(10, 2)
);

CREATE TABLE addresses (
    address_id INT PRIMARY KEY,
    city VARCHAR(50)
);

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    name VARCHAR(50),
    address_id INT,
    FOREIGN KEY (address_id) REFERENCES addresses (address_id)
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    product_id INT,
    quantity INT,
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id),
    FOREIGN KEY (product_id) REFERENCES products (product_id)
);
-- =================================================================================================================================

INSERT INTO
    products (product_id, name, price)
VALUES (301, 'Keyboard', 1200.00),
    (302, 'Mouse', 600.00),
    (303, 'Laptop', 55000.00),
    (304, 'Monitor', 8000.00);

INSERT INTO
    addresses (address_id, city)
VALUES (101, 'BBSR'),
    (102, 'Pune'),
    (103, 'CNS');

INSERT INTO
    customers (customer_id, name, address_id)
VALUES (1, 'Aditi', 101),
    (2, 'Ravi', 102),
    (3, 'Meera', NULL);

INSERT INTO
    orders (
        order_id,
        customer_id,
        product_id,
        quantity
    )
VALUES (201, 1, 301, 2),
    (202, 1, 302, 1),
    (203, 2, 303, 5);
-- =================================================================================================================================
/*
1. The operations team wants to see every order along with the customer who placed it.
*/
SELECT c.customer_id, c.name, o.order_id, o.quantity
FROM customers c
    INNER JOIN orders o ON c.customer_id = o.customer_id;

/*
2. Get order ID, customer name, and product name.
*/
SELECT
    o.order_id,
    c.name AS customer_name,
    p.name AS product_name
FROM
    customers c
    INNER JOIN orders o ON c.customer_id = o.customer_id
    INNER JOIN products p ON o.product_id = p.product_id;

/*
3. Generate a report showing Customer Name, Product Name, Quantity, and Product Price. 
*/
SELECT
    c.name customer_name,
    p.name product_name,
    o.quantity quantity,
    p.price price
FROM
    customers c
    INNER JOIN orders o ON o.customer_id = c.customer_id
    INNER JOIN products p ON o.product_id = p.product_id

/*
4. List all products and who ordered them.
*/
SELECT p.name as products, c.name as customers
FROM
    products p
    INNER JOIN orders o ON o.customer_id = p.customer_id
    INNER JOIN customers c ON o.product_id = c.product_id

/*
5. The customer support team wants to view every customer's name along with the city where they live. If address is missing 
then display city as not available.
*/

SELECT c.name as customer_name, COALESCE(a.city, 'not available')
FROM addresses a
    RIGHT JOIN customers c ON a.address_id = c.address_id;

SELECT c.name as customer_name, COALESCE(a.city, 'not available')
FROM customers c
    LEFT JOIN addresses a ON c.address_id = a.address_id;

/*
6. Find customers who haven’t placed any orders.
*/
SELECT c.*
FROM customers c
    LEFT JOIN orders o ON c.customer_id = o.customer_id
WHERE
    o.order_id is NULL;

/*
7. Total number of orders placed by each customer.
*/
SELECT
    c.customer_id,
    c.name as customer_name,
    COUNT(o.order_id) as orders_per_customer
FROM customers c
    LEFT JOIN orders o ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.name;

/*
8. Identify customers whose address is missing.
*/
SELECT * FROM customers WHERE address_id IS NULL;

/*
9. The inventory team wants to know products that have never been ordered.
*/
SELECT p.*
FROM products p
    LEFT JOIN orders o ON p.product_id = o.product_id
WHERE
    o.order_id is NULL;

/*
10. The marketing team wants cities where no customers exist.
*/
SELECT a.*
FROM addresses a
    LEFT JOIN customers c ON a.address_id = c.address_id
WHERE
    c.customer_id IS NULL;

/* 
11. Each city and number of customers living there.
*/
SELECT a.city, COUNT(c.customer_id)
FROM addresses a
    LEFT JOIN customers c ON a.address_id = c.address_id
GROUP BY
    a.city;

/*
12. Customers Who Purchased Laptop
*/
SELECT *
FROM
    customers c
    INNER JOIN orders o ON o.customer_id = c.customer_id
    INNER JOIN products p ON o.product_id = p.product_id
WHERE
    p.name = 'laptop';

-- Customers Who Have Not Purchased Laptop
SELECT c.*, o.quantity, p.*
FROM
    customers c
    LEFT JOIN orders o ON c.customer_id = o.customer_id
    LEFT JOIN products p ON o.product_id = p.product_id
    AND p.name = 'Laptop'
WHERE
    p.name IS NULL;

/*
13. Find total revenue (price * quantity) generated by each product.
*/
SELECT 
    p.product_id, 
    p.name AS product_name, 
    SUM(p.price * COALESCE(o.quantity, 0)) AS revenue
FROM products p
LEFT JOIN orders o ON p.product_id = o.product_id
GROUP BY
    p.product_id,
    p.name;

/*
14. Total spending per customer across all orders.
*/
SELECT 
    c.customer_id,
    c.name,
    COALESCE(SUM(p.price * o.quantity),0) AS total_spending
FROM customers c
LEFT JOIN orders o
    ON c.customer_id=o.customer_id
LEFT JOIN products p
    ON p.product_id=o.product_id
GROUP BY c.customer_id, c.name;


/*
15. Customers sorted by total spending (high to low).
*/
SELECT 
    c.customer_id,
    c.name,
    COALESCE(SUM(p.price * o.quantity),0) AS total_spending
FROM customers c
LEFT JOIN orders o
    ON c.customer_id=o.customer_id
LEFT JOIN products p
    ON p.product_id=o.product_id
GROUP BY c.customer_id, c.name
ORDER BY total_spending DESC;

/*
16. Management wants to know how many customers has placed more than one order.
*/
SELECT 
    c.customer_id,
    c.name,
    COUNT(o.order_id) as total_customers
FROM customers c
INNER JOIN orders o
    ON c.customer_id=o.customer_id
GROUP BY c.customer_id, c.name;
HAVING COUNT(c.customer_id)>1;


/*
17. Find the product generating maximum revenue. [price * quantity].
*/
SELECT 
    p.product_id, 
    p.name AS product_name, 
    SUM(p.price * COALESCE(o.quantity, 0)) AS revenue
FROM products p
LEFT JOIN orders o 
    ON p.product_id = o.product_id
GROUP BY
    p.product_id,
    p.name
ORDER BY revenue DESC
LIMIT 1;

/*
18.You are building a Gold layer KPI table for Power BI. Generate the following metrics in a single query:
    a. Total Customers 
    b. Total Orders 
    c. Total Products Sold 
    d. Total Revenue
*/
SELECT
    COUNT(DISTINCT c.customer_id) AS total_customers,
    COUNT(DISTINCT o.order_id) AS total_orders,
    COALESCE(SUM(o.quantity), 0) AS total_sold_products,
    COALESCE(SUM(p.price * o.quantity),0) AS total_revenue
FROM customers c
LEFT JOIN orders o
    ON c.customer_id=o.customer_id
LEFT JOIN products p
    ON p.product_id=o.product_id;

/*
19. Marketing wants to categorize customers based on total spending.
    Customer category:
        o >= 100000 🡪 'Platinum'
        o >= 10000 🡪 'Gold'
        o Silver
*/
SELECT
    c.customer_id,
    c.name,
    COALESCE(SUM(p.price*o.quantity), 0) AS total_spending,
    CASE
        WHEN  COALESCE(SUM(p.price*o.quantity), 0)>=100000 THEN 'Platinum'
        WHEN  COALESCE(SUM(p.price*o.quantity), 0)>=10000 THEN 'Gold'
        ELSE 'Silver'
    END AS customer_category
FROM customers c
LEFT JOIN orders o
    ON c.customer_id=o.customer_id
LEFT JOIN products p
    ON p.product_id=o.product_id
GROUP BY c.customer_id, c.name;

/*
20. The BI team wants to classify products based on total revenue.
product category:
>= 100000 🡪 High Revenue
>= 10000 🡪 Medium Revenue
Low Revenue
*/

SELECT 
    p.name,
    COALESCE(SUM(p.price*o.quantity), 0) as revenue,
    CASE
        WHEN COALESCE(SUM(p.price*o.quantity), 0)>= 100000 THEN 'High Revenue'
        WHEN COALESCE(SUM(p.price*o.quantity), 0)>= 1000 THEN 'Medium Revenue'
        else 'Low Revenue'
    END as product_category
FROM products p
LEFT JOIN orders o
    ON p.product_id=o.product_id
GROUP BY p.name
ORDER BY revenue DESC;


/*
21. Generate a report with product category, order size and customer address status.
    Product Category
        >=50000 🡪 'Premium'
        >=5000 🡪 'Mid Range'
        'Budget'
    Order Size
        o.quantity>=5 🡪 'Bulk'
        o.quantity>=2 🡪 'Medium'
        'Small'
    Address Status
        Address Missing
        Address Available
*/

SELECT 
    c.name,
    p.name AS product_name,
    p.price,
    o.quantity,
    (p.price * o.quantity) AS order_value,
    CASE
        WHEN COALESCE(SUM(p.price*o.quantity), 0)>=50000 THEN 'Premium'
        WHEN COALESCE(SUM(p.price*o.quantity), 0)>=5000 THEN 'Mid Range'
        else 'Budget'
    END AS product_category,
    CASE
        WHEN o.quantity>=5 THEN 'Bulk'
        WHEN o.quantity>2 THEN 'Medium'
        else 'Small'
    END AS order_size,
    CASE
        WHEN a.city IS NOT NULL THEN 'address available'
        else 'address missing'
    END as address_status
FROM customers c
INNER JOIN  a
    ON c.address_id=a.address_id
INNER JOIN orders o
    ON c.customer_id=o.customer_id
INNER JOIN products p
    ON o.product_id=p.product_id;











